first_project/first_app/urls.py
from django.conf.urls import url
from first_app import views

# TEMPLATE TAGGING
app_name = 'first_app'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^signup/', views.signup_view, name='signup'),
    url(r'^user_login/$', views.user_login, name='user_login'),
    url(r'^formpage/', views.formpage_view, name='formpage'),
]

first_project/first_project/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url
from django.conf.urls import include
from first_app import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^first_app/', include('first_app.urls')),
    url(r'^logout/$', views.user_logout, name='logout'),
    url(r'special/', views.special, name='special'),
    path('admin/', admin.site.urls),
]

first_project/first_app/models.py
from django.db import models
from django.contrib.auth.models import User

class UserProfileInfo(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    portfolio_site = models.URLField(blank=True)
    profile_pic = models.ImageField(upload_to='profile_pics', blank=True)

    def __str__(self):
        return self.user.username

class Topic(models.Model):
    top_name = models.CharField(max_length=264, unique=True)

    def __str__(self):
        return self.top_name

class Webpage(models.Model):
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    name = models.CharField(max_length=264, unique=True)
    url = models.URLField(unique=True)

    def __str__(self):
        return self.name

class AccessRecord(models.Model):
    name = models.ForeignKey(Webpage, on_delete=models.CASCADE)
    date = models.DateField()

    def __str__(self):
        return str(self.date)

first_project/first_app/forms.py
from django import forms
from django.core import validators
from django.contrib.auth.models import User
from first_app.models import UserProfileInfo


def check_name_length(value):
    if len(value) < 2:
        raise forms.ValidationError("NAME TOO SHORT!")

class FormName(forms.Form):
    name = forms.CharField(validators=[check_name_length])
    email = forms.EmailField()
    verify_email = forms.EmailField(label='Enter your email again')
    text = forms.CharField(widget=forms.Textarea)
    botcatcher = forms.CharField(
        widget=forms.HiddenInput,
        required=False,
        validators=[validators.MaxValueValidator(0)]
    )

    def clean(self):
        all_clean_data = super().clean()
        email = all_clean_data['email']
        vmail = all_clean_data['verify_email']

        if email != vmail:
            raise forms.ValidationError("EMAILS DO NOT MATCH")

class NewUserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model = User
        fields = '__all__'

class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model = UserProfileInfo
        fields = ('portfolio_site', 'profile_pic')

first_project/first_app/views.py
from django.shortcuts import render
from django.http import HttpResponse
from first_app.models import AccessRecord
from first_app import forms

from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib.auth import authenticate, login, logout

# Create your views here.
def index(request):
    webpages_list = AccessRecord.objects.order_by('date')
    date_dict = {'access_records': webpages_list}
    return render(request, 'first_app/index.html', context=date_dict)


def formpage_view(request):
    form = forms.FormName()

    if request.method == 'POST':
        form = forms.FormName(request.POST)
        if form.is_valid():
            print("VALIDATION SUCCEEDS")
            print("NAME: " + form.cleaned_data['name'])
            print("EMAIL: " + form.cleaned_data['email'])
            print("TEXT: " + form.cleaned_data['text'])
    return render(request, 'first_app/form_page.html', {'form': form})


def signup_view(request):

    registered = False
    if request.method == "POST":
        user_form = forms.NewUserForm(data=request.POST)
        profile_form = forms.UserProfileInfoForm(data=request.POST)
        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()
            profile = profile_form.save(commit=False)
            profile.user = user
            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']
            profile.save()
            registered = True
        else:
            print(user_form.errors, profile_form.errors)
    else:
        user_form = forms.NewUserForm()
        profile_form = forms.UserProfileInfoForm()

    return render(request, 'first_app/signup.html',
                            {'user_form': user_form,
                             'profile_form': profile_form,
                             'registered': registered})


def user_login(request):

    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username, password=password)
        if user:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse('index'))
            else:
                return HttpResponse("ACCOUNT NOT ACTIVE")
        else:
            print("Someone tried to log in and failed")
            print("Username: {} and password {}".format(username, password))
            return HttpResponse("invalid login details supplied")
    else:
        return render(request, 'first_app/login.html', {})


@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))


@login_required
def special(request):
    return HttpResponse("You are log in!")

first_project/templates/first_app/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
    integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
  </head>
  <body>
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <a class="navbar-brand" href="{% url 'index' %}">HOME</a>
        {% if user.is_authenticated %}
          <a class="navbar-link" href="{% url 'logout' %}">Log Out</a>
        {% else %}
          <a class="navbar-link" href="{% url 'first_app:user_login' %}">Log In</a>
        {% endif %}
        <a class="navbar-link" href="{% url 'first_app:signup' %}">Sign Up</a>
        <a class="navbar-link" href="{% url 'first_app:formpage' %}">Form</a>
        <a class="navbar-link" href="{% url 'admin:index' %}">Admin</a>
      </div>
    </nav>

    <div class="container">
    {% block body_block %}
    {# Anything outside of this will be inherited if you use extend.#}
    {% endblock %}
    </div>

  </body>
</html>

first_project/templates/first_app/form_page.html
<!DOCTYPE html>
{% extends "first_app/base.html" %}
  {% block body_block %}
    <h1>Fill out the form!</h1>
    <div class="container">
      <form method="POST">
          {{ form.as_p }}
          {% csrf_token %}
        <input type="submit" class="btn btn-primary" value="Submit">
      </form>
    </div>
 {% endblock %}

first_project/templates/first_app/index.html
<!DOCTYPE html>
{% extends "first_app/base.html" %}
  {% block body_block %}
    <h1>Welcome to Django!</h1>

    <h2>Here are your access records:</h2>
    <div class="djangotwo">
      {% if access_records %}
        <table>
          <thead>
            <th>Site Name</th>
            <th>Date Accessed</th>
          </thead>

          {% for acc in access_records %}
          <tr>
            <td>{{ acc.name }}</td>
            <td>{{ acc.date }}</td>
          </tr>
          {% endfor %}
        </table>
      {% else %}
        <p>No access records found</p>
      {% endif %}
    </div>
  {% endblock %}

first_project/templates/first_app/login.html
{% extends 'first_app/base.html' %}
  {% block body_block %}
    <div class="jumbotron">
      <h1>Please Login</h1>
      <form action="{% url 'first_app:user_login' %}" method="post">
        {% csrf_token %}
        <label for="username">Username:</label>
        <input type="text" name="username" placeholder="Enter Username" value="">
        <label for="password">password:</label>
        <input type="password" name="password">
        <input type="submit" name="" value="login">
      </form>
    </div>
  {% endblock %}

first_project/templates/first_app/signup.html
<!DOCTYPE html>
{% extends "first_app/base.html" %}
{% load static %}
  {% block body_block %}
    <div class="jumbotron">
      {% if registered %}
        <h1>Thank you for registering!</h1>
      {% else %}
        <h1>Register Here!</h1>
        <h3>Fill out the form:</h3>

        <form enctype="" method="post">
          {% csrf_token %}
          {{ user_form.as_p }}
          {{ profile_form.as_p }}
          <input type="submit" name="" value="Submit">
        </form>
      {% endif %}
    </div>
  {% endblock %}